services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDISHOST: redis
      REDISPORT: 6379
      DB: 1
      DECODE: "true"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]


  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data: